repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py313-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        name: Check for merge-conflicts
      - id: check-yaml
        name: Check for un-parseable yaml
        args: [--allow-multiple-documents]
      - id: check-executables-have-shebangs
        name: Check shell script for shebang lines
      - id: check-shebang-scripts-are-executable
        name: Check shell scripts are executable
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.23
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
     # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=MOT,hass,wee,Fo
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args:
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --warn-unreachable
          - --report-deprecated-as-note
          - --pretty
          - --namespace-packages
          - --explicit-package-bases
          - --show-error-codes
          - --show-error-context
          - --follow-untyped-imports
        additional_dependencies:
          - structlog
          - pytest
          - watchdog
          - types-Pillow
          - types-aiofiles
          - paho-mqtt
          - pytesseract
          - pydantic
          - pydantic-settings
          - hishel
          - httpx
          - pytest-httpx
          - tzlocal
 
  - repo: https://github.com/PyCQA/bandit
    rev: '1.9.2'
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
